# Code Coverage build pipeline

variables:
  FreezeArtifactStem: 'freeze'
  FreezeFileStem: 'requirements-freeze'

trigger: none

pr: none

schedules:
- cron: "30 7 * * *" # Time is UTC
  displayName: Nightly Code Coverage Build
  branches:
    include:
      - main
  always: true

jobs:
- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Linux: ubuntu-latest }
    testRunTypes: ['CodeCoverage']
    installationType: 'PipLocal'
    pyVersions: [3.6]
    freezeArtifactStem: $(FreezeArtifactStem)
    freezeFileStem: $(FreezeFileStem)