variables:
  FreezeArtifactStem: 'freeze'
  FreezeFileStem: 'requirements-freeze'

pr:
- main
- release/*

trigger: none # No CI build

pool:
  vmImage: 'ubuntu-latest'

jobs:
- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Linux: ubuntu-latest }
    installationType: 'PipLocal'
    pyVersions: [3.9]
    freezeArtifactStem: $(FreezeArtifactStem)
    freezeFileStem: $(FreezeFileStem)

- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Windows: vs2017-win2016 }
    installationType: 'PipLocal'
    pyVersions: [3.6]
    freezeArtifactStem: $(FreezeArtifactStem)
    freezeFileStem: $(FreezeFileStem)
    
- template: templates/all-tests-job-template.yml
  parameters:
    platforms: { MacOS: macos-latest }
    testRunTypes: ['Unit']
    installationType: 'None'
    pyVersions: [3.7, 3.8]
    freezeArtifactStem: $(FreezeArtifactStem)
    freezeFileStem: $(FreezeFileStem)

- template: templates/limited-installation-job-template.yml
