trigger:
- master
- dev

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
      - master
      - dev
  always: true

jobs:
- Testing
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5' 
      addToPath: true

  - script: pip install -r requirements.txt
    displayName: 'Install required packages'

  - script: flake8 .
    displayName: "Run flake8"

  - script: python -m pytest test/ --junitxml=./TEST-TEST.xml 
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()

- Code Scans
  pool:
    vmImage: ''windows-latest''
    
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      outputFormat: csv
      debugMode: false
    continueOnError: true

