[tool.black]
line-length = 88
target_version = ['py37', 'py38', 'py39', 'py310', 'py311']
preview = true
extend-exclude = '''
(
    ^/docs/
    | ^/examples/
)
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    "error",

    # Warnings in all-deps
    "default:You are about to use a dataset with known fairness issues:Warning",
    "default:Auto-removal of overlapping axes is deprecated:Warning",
    "default:DataFrame is highly fragmented:Warning",

    # Warnings in other-ml (tensorflow)
    "default:The initializer GlorotNormal is unseeded:UserWarning",
]
