blank_issues_enabled: false

contact_links:
  - name: Usage Questions - Discord community
    url: https://discord.gg/R22yCfgsRn
    about: Please ask usage questions here.
  - name: Usage Questions - StackOverflow
    url: https://stackoverflow.com/questions/tagged/fairlearn
    about: Please ask usage questions here and tag them with `fairlearn`.
