parameters:
  name: 'Notebooks'
  vmImage: 'ubuntu-latest'
  pyVersions: [3.5, 3.6, 3.7]
  pinRequirements: False
  requirementsFile: 'requirements.txt'

jobs:
- job:  ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 2
    matrix:
      ${{ each pyVer in parameters.pyVersions }}:
        ${{ pyVer }}:
          PyVer: ${{ pyVer }}

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true
  
  - template: python-infra-upgrade-steps-template.yml

  - script: python scripts/requirements_pin.py --input requirements.txt --output requirements-fixed.txt --loglevel INFO
    displayName: "Pin Requirements file"
    condition: eq('${{parameters.pinRequirements}}', True)

  - script: pip install -r ${{ parameters.requirementsFile }}
    displayName: 'Install required packages specified in ${{ parameters.requirementsFile }}'

  - script: pip install -e .
    displayName: 'Install fairlearn in edit mode'

  - script: python -m pytest test/ -m notebooks --ignore=test/perf --junitxml=./TEST-TEST.xml -o junit_suite_name="$(Agent.JobName)"
    displayName: 'Run notebooks as tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()
