name: nightly

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  all-deps:
    strategy:
      # Keep running remaining matrix jobs even if one fails
      # to see all issues rather than just the first failure.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-14]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        requirementsPinned: ["true", "false"]
    uses: ./.github/workflows/test-all-deps.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      requirementsPinned: ${{ matrix.requirementsPinned }}
      codeCovPython: "3.12"

  minimal-deps:
    strategy:
      # Keep running remaining matrix jobs even if one fails
      # to see all issues rather than just the first failure.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-14]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/test-minimal-deps.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      codeCovPython: "3.12"

  other-ml:
    strategy:
      # Keep running remaining matrix jobs even if one fails
      # to see all issues rather than just the first failure.
      fail-fast: false
      matrix:
        mlpackage: [lightgbm, xgboost, tensorflow, pytorch]
    uses: ./.github/workflows/test-other-ml.yml
    with:
      os: ubuntu-latest
      python: "3.12"
      mlpackage: ${{ matrix.mlpackage }}


  linting:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.12"]
    uses: ./.github/workflows/linting.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
